{
 "title": "Twtxt",
 "description": "Dashboard for the Job Engine",
 "tags": [
  "dashboard",
  "je"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "How long je has been up for",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurationms",
   "valueName": "current",
   "targets": [
    { "expr": "twtd_server_uptime / 1e6" }
   ]
  },
  {
   "title": "Cache Size",
   "type": "singlestat",
   "description": "Size of the global feed cache",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "twtd_cache_size" }
   ]
  },
  {
   "title": "Cache Perf",
   "type": "singlestat",
   "description": "Cache Performance (last feed cycle processed time in seconds)",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "twtd_cache_last_processed_seconds"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "CPU Usage (%)",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"twtxt\"}[5m]) * 100)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory Usage",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"twtxt\"}",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "Cache Performance",
   "type": "graph",
   "description": "Cache Performance such as last processing time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "twtd_cache_last_processed_seconds",
     "legendFormat": "s"
    }
   ]
  },
  {
   "title": "DB/Cache Stats",
   "type": "graph",
   "description": "Database / Cache Statistics (such as no. of users, feeds, sessions, cache size, etc)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "twtd_db_feeds", "legendFormat": "feeds" },
    { "expr": "twtd_db_sessions", "legendFormat": "sessions" },
    { "expr": "twtd_db_users", "legendFormat": "users" },
    { "expr": "twtd_cache_size", "legendFormat": "twts" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage of process",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"twtxt\"}[5m]) * 100)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage of process (resident, virtual)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"twtxt\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"twtxt\"}",
     "legendFormat": "vm"
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "graph",
   "description": "Memory usage as sen by Go runtime",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"twtxt\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"twtxt\"}",
     "legendFormat": "mcache"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"twtxt\"}",
     "legendFormat": "mspan"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"twtxt\"}",
     "legendFormat": "other"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"twtxt\"}",
     "legendFormat": "stack"
    },
    {
     "expr": "go_memstats_sys_bytes{job=\"twtxt\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "graph",
   "description": "Memory allocations (bytes, heap, stack)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"twtxt\"}",
     "legendFormat": "bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"twtxt\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"twtxt\"}",
     "legendFormat": "stack"
    }
   ]
  },
  {
   "title": "Threads / Goroutines",
   "type": "graph",
   "description": "Active threads / goroutines",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"twtxt\"}",
     "legendFormat": "threads"
    },
    {
     "expr": "go_goroutines{job=\"twtxt\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "description": "Garbage Collection duration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=\"twtxt\"} / go_gc_duration_seconds_count{job=\"twtxt\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"twtxt\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"twtxt\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}